Add diagnostic pragma for unused variable
arduino-libraries/WiFi pull request #41
Opened 2021-06-01 13:23 UTC by econeale

When compiling with -Wall and -Wextra GCC flags for ESP32 targets, the "initialized" variable as unused even though it is used in several macros. Adding this diagnostic pragma suppress the warning. A better solution would be to re-architect the library to avoid the WAIT_FOR_SLAVE_SELECT macro in favor of a proper function but it is unclear how this would impact other targets.

2021-07-22 07:40 UTC, aentinger commented on src/utility/spi_drv.h
> +#pragma GCC diagnostic ignored "-Wunused-variable"
```suggestion
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused-variable"
static bool initialized = false;
#pragma GCC diagnostic pop
```

2021-07-22 07:41 UTC, aentinger approved these changes
I'm not happy about such kind of fixes but I align on your reasoning. Still I'd prefer the way I've outlined above, as otherwise the unused variable warning will be disabled for the whole file (and potentially further, as its a header file).

2021-07-22 16:02 UTC, econeale commented
Push/pop is a good compromise as far as I'm concerned.

2021-07-23 04:17 UTC, aentinger requested changes

2021-07-23 04:17 UTC, aentinger commented on src/utility/spi_drv.h
>  static bool initialized = false;
This will still need to be removed though, otherwise you have a double declaration ;)

2023-08-04 13:19 UTC, closed without merging